pr:
  - master

pool:
  vmImage: ubuntu-20.04

trigger:
  branches:
    include:
      - "master"
  paths:
    include:
      - "*"

resources:
  repositories:
    - repository: templates
      type: github
      name: ensono/stacks-pipeline-templates
      ref: refs/tags/v1.1.0
      endpoint: ensonostacks

variables:
  - name: pool_vm_image
    value: ubuntu-20.04
  - name: version_spec
    value: 18.x
  - name: self_repo
    value: amido.github.io
  - name: working_directory
    value: "$(Agent.BuildDirectory)/s/$(self_repo)"
  - group: stacks-github-pages

steps:
  - checkout: self
    persistCredentials: true
  - checkout: templates

  # Install dependencies
  - template: azDevOps/azure/templates/v2/steps/build-install-dependencies-node.yml@templates
    parameters:
      versionSpec: $(version_spec)
      workingDirectory: $(working_directory)

  - bash: |
      npm run lint
    displayName: "Lint: Run markdown lint"
    workingDirectory: $(working_directory)
