pr:
  - master

pool:
  vmImage: ubuntu-18.04

trigger:
  branches:
    include:
      - 'master'
  paths:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: amido/stacks-pipeline-templates
      ref: refs/tags/v1.1.0
      endpoint: amidostacks

variables:
  - name: pool_vm_image
    value: ubuntu-18.04
  - name: version_spec
    value: 16.x
  - name: self_repo
    value: amido.github.io
  - name: working_directory
    value: '$(Agent.BuildDirectory)/s/$(self_repo)'
  - group: amido-stacks-webapp

steps:
  - checkout: self
    persistCredentials: true
  - checkout: templates

  # Install dependencies
  - template: azDevOps/azure/templates/v2/steps/build-install-dependencies-node.yml@templates
    parameters:
      versionSpec: $(version_spec)
      workingDirectory: $(working_directory)

  - bash: |
      npm run lint
    displayName: 'Lint: Run markdown lint'
    workingDirectory: $(working_directory)

  - bash: |
      git config --global user.email $(GIT_USER_EMAIL)
      git config --global user.name $(GIT_USER_NAME)
      echo "machine github.com login $(GIT_USER_NAME) password $(GITHUB_TOKEN)" > ~/.netrc
      GIT_USER="$(GIT_USER_NAME)" npm run publish
    displayName: "Publish: GitHub Pages"
    workingDirectory: $(working_directory)
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/master'), succeeded())
