== Configure NodeJS application for Azure!

Configures your NodeJS application to use various Azure services:

- https://www.npmjs.com/package/applicationinsights[App Insights]
- ...more to come.

=== Setting up @ensono-stacks/azure-node

Install the `@ensono-stacks/azure-node` with the following command:

[source, bash]
npm install --save-dev @ensono-stacks/azure-node@latest

or

[source, bash]
yarn add --dev @ensono-stacks/azure-node@latest

=== Executors and Generators

To see a list of the plugin capabilities run the following command:

[source, bash]
nx list @ensono-stacks/azure-node
```

View additional information about a plugin capability through the following command:

[source, bash]
nx g @ensono-stacks/azure-node:[generator-executor-name] --help

=== Generators


.Installs and configures a ReactJS Library with App Insights.
[%collapsible]
====
include::app-insights.adoc[]
====

.Configure Deployment & Infra for application insights
[%collapsible]
====
include::app-insights-deployment.adoc[]
====

