== @ensono-stacks/[plugin-name]

Summary of the plugin
What is its purpose?

What benefits does it give you?

=== Setting up @ensono-stacks/[plugin-name]

=== Prerequisites

Are there any prerequisites?

=== Installation 

Install the @ensono-stacks/[plugin-name] with the following command:

[source, bash]
npm install --save-dev @ensono-stacks/[plugin-name]

or

[source, bash]
yarn add --dev @ensono-stacks/[plugin-name]

=== Has it installed any additional plugins 

What are they? Can we link to docs about the additional plugins?

=== Has it created any scripts

How do we use them, what do those scripts do?
e.g

.Example script that's created
[source, json]
----
"scripts": {
  "prepare": "husky install"
}
----

=== Executors and Generators

To see a list of the plugin capabilities run the following command:

[source, bash]
nx list @ensono-stacks/[plugin-name]

View additional information about a plugin capability through the following command:

[source, bash]
nx g @ensono-stacks/[plugin-name]:[generator-executor-name] --help

=== Generators

include::executor-generator-template.adoc[]




