= Automated Accessibility Testing With Axe
:id: accessibility_testing
:sidebar_label: Automated Accessibility Testing
:hide_title: false
:hide_table_of_contents: true
:description: Accessibility testing with Axe
:keywords: axe, tests, testing, jest, cypress, accessibility testing

[CAUTION]
====
We recommend and already have support within link:./testing_in_nx/playwright_accessibility_testing.adoc[Playwright for Axe] and link:./testing_in_nx/cypress_accessibility_testing.adoc[Cypress for Axe]!
====

== Axe: Accessibility testing

From the Dequeue family of products, we are using link:https://www.deque.com/axe/[aXe] for accessibility testing. When developing, we expect to support WCAG 2.1 Level AA ["wcag21aa"] at a minimum.

aXe tests are performed on two levels:

1. Rendering the React component and testing with Jest.
2. Rendering the entire page and testing with Cypress.

=== Cypress: Debugging Axe failures

"When accessibility violations are detected, your test will fail, and an entry titled "A11Y ERROR!" will be added to the command log for each type of violation found (they will be above the failed assertion). Clicking on those will reveal more specifics about the error in the DevTools console."
-- Source: link:https://github.com/avanslaars/cypress-axe#standard-output[cypress-axe#standard-output]


For information on how to fix the failure, follow the HelpUrl printed to the console.
