---
id: testcafe_functional_testing
title: Functional Testing with TestCafe
linkTitle: TestCafe - Functional Testing
weight: 6
keywords:
  - TestCafe
  - tests
  - testing
  - functional
  - template
  - example
  - run TestCafe tests
  - TestCafe report
---

[CAUTION]
TestCafe is no longer supported by stacks. However this is still part of the scaffolding cli for testing and may be removed at a later date

link:https://devexpress.github.io/testcafe/[TestCafe] is a Node.js end-to-end open source automation tool that is used to test web applications. It can run your tests on any browser without having to download separate drivers for each browser. It is easy to install, configure, and get started without any external libraries or plugins required.

== TestCafe: Functional tests

Templated sample TestCafe automation framework for PROJECT_NAME, bootstrapped using `@amidostacks/scaffolding-cli`.

=== Running tests locally

==== Prerequisites

* Ensure that link:https://nodejs.org/[Node.js] and link:https://www.npmjs.com/[npm] are installed with the versions specified in `./package.json` file.
* Execute the following command to install all dependencies:
+
[source,bash]
----
npm install
----

* Configure your browser:
    ** Ensure you have at least one browser installed on your operating system e.g. Chrome.
    ** Include the browser name in the `./.testcaferc.json` file. e.g.:
+
[source]
----
"browsers": [
  "chrome:headless",
  "firefox:headless"
]
----

At the moment, Chrome is set as the default web browser.

To bypass the browser config in the `./.testcaferc.json` config file, simply run passing in the browser arg:

[source,bash]
----
npm run test:e2e --chrome
----

See link:https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/[browsers] for more information.

* Configure Environment Variables

TestCafe functional tests are configured to run after successful deployment, so environment variables need to be set.

Export the following environment variables.
----
- NODE_ENV,
- APP_BASE_URL: base URL to the environment where the web app is deployed,
- APP_BASE_PATH: path to the main page,
- MENU_API_URL: base URL to REST API.
----

==== Example

.UNIX
[source,bash]
----
export APP_BASE_PATH=/web/stacks
----

.WINDOWS
[source,bash]
----
set APP_BASE_PATH=/web/stacks
----

or use the ./.env file to specify the default values instead of exporting them locally.

=== Run Tests

[source,bash]
----
npm run test:e2e
----

Run tests in a specific browser:

[source,bash]
----
npm run test:e2e --chrome
----

This should launch TestCafe and run the tests in the browsers specified in `./.testcaferc.json` in the headless mode.

== Running tests in Docker

In order to be able to run these tests across environments and as part of CI, we need to use Docker to run them.

=== Build

[source,bash]
----
npm install
----

=== Run

[source,bash]
----
docker pull testcafe/testcafe:latest
----
[source,bash]
----
docker run -e APP_BASE_URL=$APP_BASE_URL -e APP_BASE_PATH=$APP_BASE_PATH -e MENU_API_URL=$MENU_API_URL -e NODE_ENV=$NODE_ENV -it -v $(pwd):/tests testcafe/testcafe chromium /**/*.test.cf.ts
----

== Optional: Running tests with Lambdatest

link:https://www.lambdatest.com[Lambdatest] is a cloud-based cross-browser testing tool that allows checking the web application functionality and other dependencies across various browsers over the internet.

=== Dependencies

An active link:https://accounts.lambdatest.com/dashboard[Lambdatest Account]

=== Settings

Export link:https://www.lambdatest.com/support/docs/npm-plugin-for-testcafe-integration-with-lambdatest/[Lambdatest Credentials] as follows:

.UNIX
[source,bash]
----
export LT_USERNAME= {your Lambdatest username}
export LT_ACCESS_KEY= {your Lambdatest access_key}
----

.WINDOWS
[source,bash]
----
set LT_USERNAME= {your Lambdatest username}
set LT_ACCESS_KEY= {your Lambdatest access_key}
----

=== Running E2E tests with LambdaTest

[source,bash]
----
npm run test:e2e -- "lambdatest:IE@11.0:Windows 10"
----

Lambdatest will create a tunnel to run the tests and automatically record videos.

The full list of browser configurations available can be found by running the following in the root:

[source,bash]
----
node_modules/.bin/testcafe -b lambdatest
----
