---
id: quickstart_java
title: Getting started with the Java Rest API application
linkTitle: Getting started
weight: 4
keywords:
  - java
  - rest
  - api
  - application
  - spring boot
  - authorization
  - docker
  - swagger
  - auth0
  - settings
  - get started
---

== Using the repository to build the Java Spring Boot Rest API application

=== Running the application locally

==== Clone one of the Java workloads to your local machine from one of the following repos
    
    . Simple web API: https://github.com/Ensono/stacks-java[stacks-java repository]
    . Web API with CQRS: https://github.com/Ensono/stacks-java-cqrs[stacks-java-cqrs repository]
    . Web API with CQRS and events: https://github.com/Ensono/stacks-java-cqrs-events[stacks-java-cqrs-events repository]
   
==== Configure the application

====
The application is currently configured to work with the Azure environment only.
====

It uses an Azure **CosmosDB** database to store the example application data. So you should have access to an instance to use with the application.
   
====
For running on a local environment you can use the /docs/workloads/azure/backend/java/setting_up_cosmos_db_locally_java[Cosmos DB emulator] (CosmosDB Emulator has a known fixed key). There is no need for CosmosDB for the simple web API implementation (1.i above) as there is no persistence layer in it. 
For further info please follow the https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21[link].
====

Set the cosmosdb URI, databaseName and key in main application configuration file (`application.yml`) using the values coming from the CosmosDB Emulator UI.

.application.yml
[source, yaml]
----
azure:
 cosmosdb:
   uri: xxxxxx
   database: xxxxxx
   key: xxxxxx
----

In addition, Azure **ApplicationInsights** is used for logging purposes. If this is unavailable, modify the application so that it doesn't fail to startup if it can't access ApplicationInsights, and simply log to the terminal instead.

.application.yml
[source, yaml]
----
application-insights:
  instrumentation-key: xxxxxx
  enabled: false
----

Alternatively, you can use Spring `local` profile, which is configured to not require cloud infrastructure to run. For the details, please follow the https://www.baeldung.com/spring-profiles#4-jvm-system-parameter[Spring Profiles] article.

There are two corresponding environment variables that need to be set to interact with these systems:

[source, text]
----
COSMOSDB_KEY
AZURE_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY
----

.Unix
Set the two environment variables as additional variables within e.g. ~/.profile or /etc/profile.

.Windows
Open the System Properties then select the Advanced tab, then click on the Environment Variables
button and add the new parameters.

   
==== Build and run the application

Note that at a minimum https://adoptopenjdk.net/[Java 11] should be installed.

Move to the `<PROJECT-NAME>/java` folder, then

.Unix
[source, bash]
----
./mvnw spring-boot:run
----

.Windows
[source, bash]
----
mvnw.cmd spring-boot:run
----

For instructions on how to customise the project for your company please look in the link:../../../common/backend/java/scaffolding_java.adoc[Scaffolding] section

=== Build and run the application using Cosmos DB Emulator
    
Please refer to section "Determine which root certificates have been installed" in
link:../../backend/java/setting_up_cosmos_db_locally_java.adoc[Setting Up CosmosDB Emulator]

Move to the `<PROJECT-NAME>/java` folder, then go to `application.yml` either comment out the `application-insights` block or set `enabled`  property to `false`.
    
In `logback-spring.xml` comment out two sections relating to the application-insights (both the appender and the logger).

.logback-spring.xml
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
  <configuration>
    <appender class="ch.qos.logback.core.ConsoleAppender" name="console">
      <encoder>
        <pattern>%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) | %X{CorrelationId} |
          %highlight(%-5level) %logger{36}.%M - %msg%n
        </pattern>
      </encoder>
    </appender>
    <!-- <appender class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender"
      name="aiAppender">
    </appender> -->
    <root level="info">
      <appender-ref ref="console"/>
    </root>
    <!-- <root level="info">
      <appender-ref ref="aiAppender"/> -->
  </root>
</configuration>
----

Set `COSMOSDB_KEY` as an environment variable and set the value to be the primary key value on the emulator.

.Unix
[source, bash]
----
./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-Djavax.net.ssl.trustStore="<Location of the root cosmos db certificate>" -Djavax.net.ssl.trustStorePassword="changeit"'
----

.Windows
[source, bash]
----
mvnw.cmd spring-boot:run -Dspring-boot.run.jvmArguments='-Djavax.net.ssl.trustStore="<Location of the root cosmos db certificate>" -Djavax.net.ssl.trustStorePassword="changeit"'
----


==== Verify that the application has started

Browse to http://localhost:9000/v1/menu[http://localhost:9000/v1/menu]. This should return a valid JSON response.

The application configuration uses Swagger/OAS3 to represent the API endpoints. The Swagger UI can be viewed by directing your
browser to http://localhost:9000/swagger/index.html[http://localhost:9000/swagger/index.html].

==== Authorization

All API endpoints are (optionally) protected using **Auth0**. There is an `auth.properties` file within the project codebase.
If the following property within this file is set:

[source, text]
auth.isEnabled=true

then clients will need to pass an `Authorization` header containing the Bearer token generated from Auth0 as part of the endpoint request. If the value
is set to `false` then no authorization is required.

==== Auth0 configuration properties

If using Auth0 for authorization, Auth0 itself will need to be configured with both an API definition and an associated Application.
There are corresponding configuration values required for the Ensono Stacks application, within the `auth.properties` file, e.g.

[source, text]
auth0.issuer=https://amidostacks.eu.auth0.com/
auth0.apiAudience=https://amidostacks.eu.auth0.com/api/v2/

These parameters are used to verify that the JWT supplied in the Authorization header of a request is valid.

==== Swagger/OAS

- Automatically generated for the project. Go to http://localhost:9000/swagger/index.html[Swagger Index] to view.
- Swagger Json is here: http://localhost:9000/swagger/oas.json[Swagger Json]

==== Health check

- Available at: http://localhost:9000/health[health check]
(This can also be configured to run on another port)

== Using a Docker image

<https://docs.docker.com/docker-for-windows/install/>

From the `<PROJECT-NAME>/java` folder, build a Docker image using e.g. the command below:

[source, bash]
----
docker build --tag stacks:1.0 .
----

This uses the `Dockerfile` in this folder to generate the Docker image.

If you have an `.m2` directory in the `java/` folder, the Docker build will attempt to copy the files inside the container and use the cached versions.

Once the Docker image is created, you can then run a Docker container based on this image using e.g.

[source, bash]
----
docker run -p 9000:9000 -e AZURE_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY -e AZURE_COSMOSDB_KEY stacks:1.0
----

which passes in the two required environment variables from your own environment.
