=== @ensono-stacks/cypress:accessibility

.Adds axe accessibility tests to your test project
[%collapsible]
=====
[.details]
====
The _accessibility_ generator installs the required plugins for conducting accessibility testing with Cypress. Additionally, this will configure your test project to enable proper test reporting from `axe` while providing you with an example set of test cases.
====

[discrete]
== Usage

----
nx g @ensono-stacks/cypress:accessibility
----

[discrete]
== Command line arguments

[cols="2*",options="header"]
|===
| Option | Description
| --project -p | The name of the test project to add accessibility tests to
|===

[discrete]
== Generator Output

Scaffolding accessibility testing will add two dependencies to the `package.json`:

1. link:https://www.npmjs.com/package/axe-core[`axe-core`] - The accessibility test engine
2. link:https://www.npmjs.com/package/cypress-axe[`cypress-axe`] - Cypress integration with the accessibility test engine

Additionally, an example accessibility test will be generated, showcasing how to utilize _axe_ to scan your application for accessibility violations:

[source,text]
----
.
├── apps
│   ├── <app-name>
│   │   ├── cypress
│   │   │   │   ├── support
│   │   │   │   │   ├── e2e.ts #Terminal logging function configured
│   │   │   │   ├── e2e
│   │   │   │   │   ├── axe-accessibility.cy.ts #Example accessibility test using cypress
│   ├── cypress.config.js #setupNodeEvents configured for logging with terminal logging function
├──   tsconfig.cy.json #cypress-axe declared as a type
└──────────
----

[NOTE]
====
Visit the link:../../testing/testing_in_nx/cypress_accessibility_testing.adoc[Accessibility Testing] documentation for further details!
====
=====
