=== @ensono-stacks/playwright:accessibility

.Adds axe accessibility tests to your test project
[%collapsible]
=====
[.details]
====
The _accessibility_ generator installs link:https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/README.md[@axe-core/playwright] and configures an example accessibility test.
====

[discrete]
== Usage

----
nx g @ensono-stacks/playwright:accessibility
----

[discrete]
== Command line arguments

[cols="1,1"]
|===
| Option | Description

| --project -p 
| The name of the test project to add accessibility tests to
|===

[discrete]
== Generator Output

Scaffolding accessibility testing will add two dependencies to the `package.json`:

1. link:https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/README.md[@axe-core/playwright] - The accessibility test engine
2. link:https://www.npmjs.com/package/axe-result-pretty-print[@axe-result-pretty-print] - Result formatter

Additionally, an example accessibility test will be generated, showcasing how to utilize both _axe_ and _axe-result-pretty-print_ to scan your application for accessibility violations.

[source,text]
----
.
├── apps
│   ├── <app-name>-e2e
│   │   ├── src
│   │   │   ├── axe-accessibility.spec.ts #Example accessibility test using Playwright
----
NOTE: Visit the link:../../testing/testing_in_nx/playwright_accessibility_testing.adoc[Accessibility Testing] documentation for further details!
=====

