---
id: ensono-stacks-cypress
title: "@ensono-stacks/cypress"
linkTitle: "@ensono-stacks/cypress"
weight: 8
keywords:
  - Nx
  - monorepo
  - stacks
  - ensono
  - cypress
  - generator
  - executor
---

[IMPORTANT]
====
Deprecated

This plugin is no longer supported. Ensono-stacks/cypress 2.0.7 is the final release version and may not be compatible with the ensono-stacks/workspace plugin above version 2.0.7. Existing users can still find information about the deprecated Cypress plugin here. 
====

Using the `@ensono-stacks/cypress` plugin can help you get started with testing using Cypress. Built upon the link:https://nx.dev/packages/cypress[@nx/cypress] plugin, Ensono Stacks provides additional capabilities to help you hit the ground running!

Additionally, Cypress tests can be added to your deployment pipelines through the various deployment generators.

NOTE: Visit the link:../../testing/testing_in_nx/frontend_testing_in_nx.md[Frontend Testing in an Nx monorepo] and link:../../testing/testing_in_nx/cypress_nx.md[Testing with Cypress] user guides for more information!


== Setting up @ensono-stacks/cypress

Install the `@ensono-stacks/cypress` plugin with the following command:

----
npm install --save-dev @ensono-stacks/cypress@latest
----

or

----
yarn add --dev @ensono-stacks/cypress@latest
----

== Executors and Generators

To see a list of the plugin capabilities, run the following command:

----
nx list @ensono-stacks/cypress
----

View additional information about a plugin capability through the following command:

----
nx g @ensono-stacks/cypress:[generator-executor-name] --help
----

=== Generators

include::init.adoc[]

include::init-deployment.adoc[]

include::accessibility.adoc[]

=== Executors

include::executor.adoc[]