---
id: build_and_run_project_netcore
title: Build & Run REST API
linkTitle: Build & Run REST API
weight: 2
keywords:
  - .net core
  - rest api
  - azure
  - application insights
  - build
  - run
  - application
---

=== Build and Run the Application

The API can be configured to run locally or in a Docker container.

==== Build and Run Locally

Instructions for Windows

[arabic]
. Open *Command Prompt* or *PowerShell*.
. Navigate to the `+<PROJECT-NAME>/simple-api/src/api+` folder.
. Run the following command to build the project:
+
[source,bash]
----
dotnet build
----
. Run the following command to start the project:
+
[source,bash]
----
dotnet run --project xxENSONOxx.xxSTACKSxx.API/xxENSONOxx.xxSTACKSxx.API.csproj
----

Instructions for Linux

[arabic]
. Open your *terminal*.
. Navigate to the `+<PROJECT-NAME>/simple-api/src/api+` folder.
. Run the following command to build the project:
+
[source,bash]
----
dotnet build
----
. Run the following command to start the project:
+
[source,bash]
----
dotnet run --project xxENSONOxx.xxSTACKSxx.API/xxENSONOxx.xxSTACKSxx.API.csproj
----

==== Build and Run in Docker Container

Instructions for Docker

[arabic]
. Open your *terminal*.
. Navigate to the `+<PROJECT-NAME>/simple-api/src/api+` folder.
. Run the following command to build a Docker image:
+
[source,bash]
----
docker build -t dotnet-api .
----
+
This uses the *Dockerfile* in this folder to generate the Docker image.
. After the Docker image is created, run the following command to start
the Docker container:
+
[source,bash]
----
docker run -p 5000:80 --mount type=bind,source=/path/to/PROJECT-NAME/simple-api/src/api/xxENSONOxx.xxSTACKSxx.API/appsettings.json,target=/app/config/appsettings.json
----

==== Verify that the Application Has Started

[arabic]
. Open your web browser.
. Go to http://localhost:5000/v1/menu. This should return a valid JSON
response.

*Note:* If you have changed the domain (originally `+Menu+`), the path
will reflect that change. For example, if your domain is `+Foo+`, then
the path will be `+../v1/foo+` instead of `+../v1/menu+`.   

[arabic, start=3]
. To view the Swagger UI, go to
http://localhost:5000/swagger/index.html. This will show the API
endpoints.