---
id: create_project_netcore
title: Create REST API project
linkTitle: Create REST API project
weight: 1
keywords:
  - .net core
  - rest api
  - example
  - template
  - azure
  - application insights
  - build
  - run
  - application
  - configure
  - docker
  - tests
  - github
---

=== Create a project using the Nuget template package

==== Install the package

[arabic]
. Go to the
https://www.nuget.org/packages/Ensono.Stacks.Templates/[Ensono.Stacks.Templates
package page on Nuget].
. Copy the command displayed on the page to install the latest version
of the package.
. Open your terminal and run the copied command. For example:

[source,bash]
----
dotnet new install Ensono.Stacks.Templates
----

==== Create a new project

[arabic]
. Open your terminal.
. Navigate to the folder where you want to create the new project.
. Run the following command to create the project:

[source,bash]
----
dotnet new stacks-webapi -n Company.Project -do YourDomain --cloudProvider Azure
----

This command will create a folder and a repository called
`+Company.Project+` with DevOps build pipelines ready for Azure DevOps.

==== Uninstalling a template

[arabic]
. Open your terminal.
. Run the following command to uninstall the template pack:

[source,bash]
----
dotnet new uninstall Ensono.Stacks.Templates
----

==== Template parameter details

* *-n|–name*
** Sets the project name.
** If you do not provide this parameter, the project name will be the
same as the folder where you run the command.
* *-do|–domain*
** Sets the name of the aggregate root object. This is also the name of
the collection within the CosmosDB instance.
* *-o|–output*
** Sets the path where the project will be created.
** If you do not provide this parameter, a new folder will be created.
* *–cloudProvider*
** Configures which cloud provider to use.
* *-cicd|–cicdProvider*
** Configures which CI/CD provider templates to use.