pr: none

pool:
  vmImage: ubuntu-18.04

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: amido/stacks-pipeline-templates
      ref: refs/tags/v1.1.0
      endpoint: amidostacks

variables:
  - name: pool_vm_image
    value: ubuntu-18.04
  - name: version_spec
    value: 12.x
  - name: self_repo
    value: stacks
  - name: working_directory
    value: '$(Agent.BuildDirectory)/s/$(self_repo)/website'
  - group: amido-stacks-webapp


steps:
  - checkout: self
  - checkout: templates
    persistCredentials: true

  # Install dependencies
  - template: azDevOps/azure/templates/v2/steps/build-install-dependencies-node.yml@templates
    parameters:
      versionSpec: $(version_spec)
      workingDirectory: $(working_directory)

  - bash: |
      git config --global user.email $(GIT_USER_EMAIL)
      git config --global user.name $(GIT_USER_NAME)
      echo "Publishing with $(GIT_USER_NAME)"
      echo "Token $(SECRET_SYSTEM_ACCESSTOKEN)"
      echo "Token $(SYSTEM_ACCESSTOKEN)"
      echo "Connection $(ENDPOINT_AUTH_SYSTEMVSSCONNECTION)"
      echo "machine github.com login <GITHUB_USERNAME> password $(GIT_USER_EMAIL)" > ~/.netrc
      GIT_USER="$(GIT_USER_NAME)" npm run publish
    displayName: "Publish: GitHub Pages"
    workingDirectory: $(working_directory)
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

 