permissions:
  contents: read
  pages: write
  id-token: write

name: stacks.website
on:
    push:
        paths:
            - 'src/**'
    pull_request:
        branches:
            - master
            - feat/ensono-rebrand
            - feat/testing-deployment
jobs:
    build:
        name: Build and Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            # Checkout the documentation repository
            - name: Checkout Repo
              uses: actions/checkout@v4
            # Configure node so that the build can run
            - name: Use NodeJS
              uses: actions/setup-node@v3
              with:
                    node-version: '16.14.x'
            # Install Node dependencies
            - name: Install Dependencies
              run: npm install
            # Build the website
            - name: Generate Website
              run: npm run build
              env:
                # Secrets from GitHub go here
                ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
                ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
                ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
                
    deploy:
        environment:
          name: github-pages
        needs: build
        steps: 
            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2