permissions:
  contents: read
  pages: write
  id-token: write
name: stacks.website
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    build-and-deploy:
        name: Build and Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            # Checkout the documentation repository
            - name: Checkout Repo
              uses: actions/checkout@v4
            # Configure node so that the build can run
            - name: Use NodeJS
              uses: actions/setup-node@v3
              with:
                    node-version: '16.*'
            # Install Node dependencies
            - name: Install Dependencies
              run: npm install
            # Build the website
            - name: Generate Website
              run: npm run build
              env:
                # Secrets from GitHub go here
                ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
            # Deploy to GHitHub Pages
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.3.3
              with:
                branch: master
                folder: build
                clean: true