permissions:
  contents: read
  pages: write
  id-token: write
name: stacks.website
on:
  push:
    paths:
      - src/**
  pull_request:
    branches:
      - master
      - feat/ensono-rebrand
      - feat/testing-deployment
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
      - name: Install Dependencies
        run: npm install
      - name: Generate Website
        run: npm run build
        env:
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
